from decimal import Decimal

DEFAULT_PAPER_ACCOUNT_USDT = Decimal("100000000")

ORDER_STATUS_NEW = "new"
ORDER_STATUS_PARTIALLY_FILLED = "partially_filled"
ORDER_STATUS_FILLED = "filled"
ORDER_STATUS_CANCELED = "canceled"
ORDER_STATUS_REJECTED = "rejected"

ORDER_TYPE_LIMIT = "limit"
ORDER_TYPE_MARKET = "market"
ORDER_TYPE_MARKET_PROTECTED = "market_protected"

SIDE_BUY = "buy"
SIDE_SELL = "sell"

PRODUCT_TYPE_SPOT = "SPOT"
PRODUCT_TYPE_PERP = "PERP"

POSITION_ACTION_OPEN = "open"
POSITION_ACTION_CLOSE = "close"

POSITION_SIDE_LONG = "long"
POSITION_SIDE_SHORT = "short"
POSITION_SIDE_FLAT = "flat"

POSITION_MODE_ONE_WAY = "one_way"
POSITION_MODE_HEDGE = "hedge"

MARGIN_MODE_ISOLATED = "isolated"
MARGIN_MODE_CROSS = "cross"

INDEX_PRICE_SOURCE_BINANCE = "binance"
INDEX_PRICE_SOURCE_MANUAL = "manual"

MARK_PRICE_MODE_ORDERBOOK = "orderbook"

FUNDING_RATE_MODE_BINANCE = "binance"
FUNDING_RATE_MODE_FORMULA = "formula"

CONTRACT_TRADING_MODE_NORMAL = "normal"
CONTRACT_TRADING_MODE_REDUCE_ONLY = "reduce_only"
CONTRACT_TRADING_MODE_PAUSED = "paused"

TIF_GTC = "gtc"
TIF_IOC = "ioc"
TIF_POST_ONLY = "post_only"

ROLE_MANUAL = "manual_user"
ROLE_USER = "user"
ROLE_BOT = "mm_bot"
ROLE_ADMIN = "admin"

PAPER_MARKET_DRAFT = "DRAFT"
PAPER_MARKET_VALIDATING = "VALIDATING"
PAPER_MARKET_PRE_OPEN = "PRE_OPEN"
PAPER_MARKET_TRADING = "TRADING"
PAPER_MARKET_PAUSED = "PAUSED"
PAPER_MARKET_CANCEL_ONLY = "CANCEL_ONLY"
PAPER_MARKET_REDUCE_ONLY = "REDUCE_ONLY"
PAPER_MARKET_DELISTING = "DELISTING"
PAPER_MARKET_DELISTED = "DELISTED"

ZERO = Decimal("0")
